services:
  # Platform-specific layer
  orin-platform:
    image: tauv/orin-platform
    build:
      context: ./platform
      dockerfile: Dockerfile.orin
  
  x86-nvidia-platform:
    image: tauv/x86-nvidia-platform
    build:
      context: ./platform
      dockerfile: Dockerfile.x86-nvidia

  # Common layer
  orin-common:
    image: tauv/orin-common
    build:
      context: ./common
      dockerfile: Dockerfile.common
      args:
        BASE_IMAGE: tauv/orin-platform
    depends_on:
      - orin-platform
  
  x86-nvidia-common:
    image: tauv/x86-nvidia-common
    build:
      context: ./common
      dockerfile: Dockerfile.common
      args:
        BASE_IMAGE: tauv/x86-nvidia-platform
    depends_on:
      - x86-nvidia-platform


  # Application layer
  tauv-x86-nvidia-workstation:
    image: tauv/workstation
    build:
      context: ./apps
      dockerfile: Dockerfile.workstation
      args:
        BASE_IMAGE: tauv/x86-nvidia-common
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /dev/dri:/dev/dri  # Mount the DRI device for GPU access TODO: Do we need this
      - ${SHARED_DIR}:/shared  # Bind the SHARED_DIR to /shared in the container
    tty: true  # Allocate a pseudo-TTY
    stdin_open: true  # Keep stdin open TODO: DO WE NEED THIS
    privileged: true
    ports:
      - 10122:22
    depends_on:
      - x86-nvidia-common
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  tauv-kingfisher:
    build:
      context: ./apps/vehicle
      dockerfile: Dockerfile.kingfisher
      args:
        - BASE_IMAGE=tauv/orin-common
    image: tauv/vehicle-kingfisher
    volumes:
      - /dev:/dev
      - /tm.X11-unix/:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /home/tartanauv/shared:/shared
      - /home/tartanauv/data:/data
    environment:
      XAUTHORITY: /tmp/.docker.xauth
    network_mode: "host"
    privileged: true
    runtime: nvidia
    depends_on:
      - orin-common
